# Generated by Django 6.0.2 on 2026-02-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('university_admin', 'University Administrator'), ('dean', 'Dean'), ('hod', 'Head of Department'), ('exam_officer', 'Exam Officer'), ('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
