from rest_framework import viewsets, filters, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django_filters.rest_framework import DjangoFilterBackend
from reports.models import Report
from reports.serializers import ReportSerializer


class ReportViewSet(viewsets.ModelViewSet):
    """ViewSet for Report model"""
    queryset = Report.objects.all()
    serializer_class = ReportSerializer
    permission_classes = [IsAuthenticated]
    
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    filterset_fields = ['report_type', 'generated_by']
    search_fields = ['title', 'description']
    ordering_fields = ['generated_at', 'title']
    ordering = ['-generated_at']
    
    @action(detail=False, methods=['get'], permission_classes=[IsAuthenticated])
    def my_reports(self, request):
        """Get reports generated by current user"""
        reports = Report.objects.filter(generated_by=request.user)
        
        page = self.paginate_queryset(reports)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)
        
        serializer = self.get_serializer(reports, many=True)
        return Response(serializer.data)
    
    @action(detail=False, methods=['post'], permission_classes=[IsAuthenticated])
    def generate_report(self, request):
        """Generate a new report"""
        report_type = request.data.get('report_type')
        title = request.data.get('title')
        filters = request.data.get('filters', {})
        description = request.data.get('description', '')
        
        if not report_type or not title:
            return Response(
                {'error': 'report_type and title are required'},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        report = Report.objects.create(
            title=title,
            report_type=report_type,
            description=description,
            generated_by=request.user,
            filters=filters
        )
        
        serializer = self.get_serializer(report)
        return Response(serializer.data, status=status.HTTP_201_CREATED)
